print("Hello, nice to meet you, Good Afternoon \n")
name= input("What is your name? \n")
live= input("Where do you live "+name+ "? \n")
pet = input("What's the name of your pet? \n")
print("\n Hello "+name+ "\n you are live in: "+live+ "\n and the name of your pet is: "+pet+ " is a really cute name")
